name: Update OSS Licenses Dist

on:
  push:
    branches:
      - main

jobs:
  update-oss-licenses-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: yarn install

      - name: Install tofrodos
        run: sudo apt-get update && sudo apt-get install tofrodos

      - name: Backup OSSLicensesDist.js
        run: |
          if [ -f pages/utils/OSSLicensesDist.js ]; then
            cp pages/utils/OSSLicensesDist.js pages/utils/OSSLicensesDist.js.bak
          else
            touch pages/utils/OSSLicensesDist.js.bak
          fi

      - name: Build OSSLicensesDist.js
        run: yarn run build-oss-licenses-dist

      - name: todos OSSLicensesDist.js
        run: todos pages/utils/OSSLicensesDist.js

      - name: Compare files
        id: compare-files
        run: |
          if ! git diff --no-index --ignore-space-at-eol pages/utils/OSSLicensesDist.js pages/utils/OSSLicensesDist.js.bak; then
            echo "files_changed=true" >> $GITHUB_ENV
          else
            echo "files_changed=false" >> $GITHUB_ENV
          fi

      - name: Delete OSSLicensesDist.js.bak
        if: env.files_changed == 'true'
        run: rm pages/utils/OSSLicensesDist.js.bak

      - name: Create Pull Request
        if: env.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: '更新开源许可证信息（OSSLicensesDist.js）'
          body: '自动化更新 OSSLicensesDist.js'
          branch: 'update-licenses'
          commit-message: 'Update OSSLicensesDist.js'
          labels: 'auto-generated'