name: Update OSS Licenses Dist

on:
  push:
    branches:
      - main

jobs:
  update-licenses:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: yarn install

      - name: Build OSSLicensesDist.js
        run: yarn run build-oss-licenses-dist

      - name: Create backup of OSSLicensesDist.js
        run: |
          if (Test-Path pages\utils\OSSLicensesDist.js) {
            Copy-Item pages\utils\OSSLicensesDist.js pages\utils\OSSLicensesDist.js.bak
          } else {
            New-Item -ItemType File -Path pages\utils\OSSLicensesDist.js.bak -Force
          }
          shell: pwsh

      - name: Compare files
        id: compare-files
        run: |
          $file1 = Get-Content pages\utils\OSSLicensesDist.js
          $file2 = Get-Content pages\utils\OSSLicensesDist.js.bak
          if (Compare-Object -ReferenceObject $file1 -DifferenceObject $file2) {
            echo "files_changed=true" >> $env:GITHUB_ENV
          } else {
            echo "files_changed=false" >> $env:GITHUB_ENV
          }
        shell: pwsh

      - name: Delete backup file
        run: |
          Remove-Item pages\utils\OSSLicensesDist.js.bak -Force
        shell: pwsh

      - name: Create Pull Request
        if: env.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: '更新开源许可证信息（OSSLicensesDist.js）'
          body: '自动化更新 OSSLicensesDist.js'
          branch: 'update-licenses'
          commit-message: 'Update OSSLicensesDist.js'
          labels: 'auto-generated'
