name: Update OSS Licenses Dist

on:
  push:
    branches:
      - main

jobs:
  update-oss-licenses-dist:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: yarn install

      - name: Build OSS Licenses Dist
        run: yarn run build-oss-licenses-dist

      - name: Fetch latest changes from remote
        run: git fetch origin main

      - name: Compare files
        id: compare-files
        run: |
          if (-not (git diff --exit-code origin/main)) {
            Write-Output "files_changed=true" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            Write-Output "files_changed=false" | Out-File -FilePath $env:GITHUB_ENV -Append
          }
        shell: pwsh

      - name: Create Pull Request
        if: env.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: '更新开源许可证信息（OSSLicensesDist.js）'
          body: '自动化更新 OSSLicensesDist.js'
          branch: 'update-licenses'
          commit-message: 'Update OSSLicensesDist.js'
          labels: 'auto-generated'