name: Update OSS Licenses Dist

on:
  push:
    branches:
      - main

jobs:
  update-oss-licenses-dist:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: source

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: yarn install

      - name: Build OSS Licenses Dist
        run: yarn run build-oss-licenses-dist

      - name: Fetch latest changes from remote
        run: git fetch origin main

      - name: Compare files (Windows)
        if: matrix.os == 'windows-latest'
        id: compare-files-windows
        run: |
          if ! git diff --exit-code origin/main; then
            echo "files_changed=true" >> $GITHUB_ENV
          else
            echo "files_changed=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Compare files
        if: matrix.os != 'windows-latest'
        id: compare-files
        run: |
          if ! git diff --exit-code origin/main; then
            echo "files_changed=true" >> $GITHUB_ENV
          else
            echo "files_changed=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: '更新开源许可证信息'
          body: '自动化更新 npm 依赖项的开放源代码信息'
          branch: 'update-licenses'
          commit-message: 'Update OSS Licenses Dist'
          labels: 'auto-generated'
