name: Update OSS Licenses Dist

on:
  push:
    branches:
      - main

jobs:
  update-oss-licenses-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: source

    strategy:
      matrix:
        file:
          - pages/utils/OSSLicensesDist.js

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: yarn install

      - name: Install tofrodos
        run: sudo apt-get update && sudo apt-get install tofrodos

      - name: Backup ${{ matrix.file }}
        run: |
          if [ -f ${{ matrix.file }} ]; then
            cp ${{ matrix.file }} ${{ matrix.file }}.bak
          else
            touch ${{ matrix.file }}.bak
          fi

      - name: Build ${{ matrix.file }}
        run: yarn run build-oss-licenses-dist

      - name: todos ${{ matrix.file }}
        run: todos ${{ matrix.file }}

      - name: Compare files for ${{ matrix.file }}
        id: compare-files
        run: |
          if ! git diff --no-index --ignore-space-at-eol ${{ matrix.file }} ${{ matrix.file }}.bak; then
            echo "files_changed=true" >> $GITHUB_ENV
          else
            echo "files_changed=false" >> $GITHUB_ENV
          fi

      - name: Delete ${{ matrix.file }}.bak
        if: env.files_changed == 'true'
        run: rm ${{ matrix.file }}.bak

      - name: Create Pull Request for ${{ matrix.file }}
        if: env.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: '更新开源许可证信息（${{ matrix.file }}）'
          body: '自动化更新 ${{ matrix.file }}'
          branch: 'update-licenses-${{ matrix.file }}'
          commit-message: 'Update ${{ matrix.file }}'
          labels: 'auto-generated'
